# Setup
title:        Beauty is life
tagline:      Beauty
baseurl:      ""
locale:       "en"

# About/contact
author:
  name:       Z Peng
  url:        http://github.com/zhongpenggeo/ 

# Gems
gems:
  - jekyll-paginate

#Others
#markdown: kramdown
paginate: 10
paginate_path: "page:num"
