title: Beauty is Life
description: My Personal Blog
author: Z Peng
logo: /hcz-jekyll-blog/static/img/cat.jpg
github: https://github.com/zhongpenggeo
about: scientific reserch interests

baseurl: ""
url: ""

allowsearch: true

disqus_shortname: 
google_analytics: 

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
